### ISSUE TITLE
[BUG] Doesn't support cargo workspaces

### ISSUE THREAD

**Issue by zacps** [JScearcy/rust-doc-viewer#8] opened 2019-09-13 21:54 UTC
**Describe the bug**
Documentation fails to open when working on a project that uses cargo workspaces.

**To Reproduce**
1. Create a workspace
2. Create a crate in the workspace with some documentation
3. Run `cargo doc`
4. Run `Rust: Doc Viewer`
5. Error: Could not open the rust docs from ...

**Expected behaviour**
Attempts to open the index file located at `ROOT/folder_name/target/doc/crate_name/index.html`

**Actual behaviour**
Attempts to open the index file at `ROOT/folder_name/target/doc/index.html`

**Comment by JScearcy** [comment] 2019-09-14 01:05
I did reproduce this issue - I'll look into this further

**Comment by JScearcy** [comment] 2019-09-14 05:38
This change is deployed to VSCode Marketplace - feel free to test, I've tested Windows and Linux with success

**Comment by zacps** [comment] 2019-09-16 02:10
This fixes the main issue, but I think I might have found another.

If the crate name contains dashes cargo converts them to underscores. From what I can tell given a crate name of `contains-dash` the extension will look for the docs with a crate name of `contains-dash` but it will be under `contains_dash`.

I didn't test this thoroughly though so I may just be doing something wrong.

**Comment by JScearcy** [comment] 2019-09-16 02:37
Aghh, you're right. I remember noticing this issue initially and I didn't make a note of the problem, then never got around to fixing it.

**Comment by JasperDeSutter** [comment] 2019-09-17 08:39
Another issue is when crates are under a subfolder as in:
`
members = [
    "crates/my-crate"
]
`
* Attempts to open the index file located at "./target/doc/crates/my_crate/index.html"
* Should open the index file at "./target/doc/my_crate/index.html"

And one more issue is with the possibility to define wildcard crates like this:
`
members = [
    "crates/*"
]
`
* Shows option to open the index file located at "./target/doc/crates/*/index.html"
* Should be expanded to all crates under "crates/"

For info, this is used here: https://github.com/rust-analyzer/rust-analyzer/blob/master/Cargo.toml

**Comment by JScearcy** [comment] 2019-09-18 04:14
Turns out I missed the RFC when I was looking for documentation with regards to this. I'll be adding support based off of [RFC-1525](https://github.com/rust-lang/rfcs/blob/master/text/1525-cargo-workspace.md)

**Comment by JScearcy** [comment] 2019-10-09 06:36
Alright, closing this, the extension will now handle workspaces as expected

**Closed by JScearcy** 2019-10-09 06:36 UTC
Labels: bug
